# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kugo < Formula
  desc "Golang based CLI for Jenkins API."
  homepage "https://github.com/tkennes/kugo"
  version "1.0.20"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.20/kugo_1.0.20_Darwin_x86_64.tar.gz"
      sha256 "450b93fdcc9d70097c3ff8966485ba4461e06f6a4bf66b922588bde0adc9bd8e"
    end
    if Hardware::CPU.arm?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.20/kugo_1.0.20_Darwin_arm64.tar.gz"
      sha256 "ead0845c3309788f58f514cd34d0f18df671d1025a06c58779559e99e98bf27e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.20/kugo_1.0.20_Linux_x86_64.tar.gz"
      sha256 "5d33c782c35c1357a00821a3b4bfc1e74a4194190a7e95315d60601e716e546c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.20/kugo_1.0.20_Linux_arm64.tar.gz"
      sha256 "edd837d3b9846f0e879814f5082ae2d028d860975b6f3fdffd9818248f5a3204"
    end
  end

  depends_on "go" => :build

  def install
    bin.install "kugo"
  end

  test do
    assert shell_output("#{bin}/kugo version")
  end
end
