# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kugo < Formula
  desc "Golang based CLI for Jenkins API."
  homepage "https://github.com/tkennes/kugo"
  version "1.0.18"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.18/kugo_1.0.18_Darwin_x86_64.tar.gz"
      sha256 "85c525b5f4130723c9feb0bce9acc61b67416a722f35997bd9c950361eb29070"
    end
    if Hardware::CPU.arm?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.18/kugo_1.0.18_Darwin_arm64.tar.gz"
      sha256 "47afae2b2b7e16f0ad0c8284a36ccb19ef7ed1c6d4ddda8e8ff83e8313e2f9bf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.18/kugo_1.0.18_Linux_x86_64.tar.gz"
      sha256 "abe752c2dbb1860b386201b1aeaabf0100b7f425ede13c75618f79021be26a65"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/tkennes/kugo/releases/download/v1.0.18/kugo_1.0.18_Linux_arm64.tar.gz"
      sha256 "a3f2274a953518258cdf3b90136fd7e35107592b6193508b4a49cf5b513a463a"
    end
  end

  depends_on "go" => :build

  def install
    bin.install "kugo"
  end

  test do
    assert shell_output("#{bin}/kugo version")
  end
end
